version: 2

models:
  - name: clientes_ephemeral
    description: "Modelo ephemeral para limpiar datos de clientes"
    columns:
      - name: id
        tests:
          - not_null

  - name: clientes_view
    description: "Vista basada en clientes_ephemeral"
    columns:
      - name: id
        tests:
          - unique
          - not_null

  - name: clientes_table
    description: "Tabla con transformación adicional"
    columns:
      - name: id
        tests:
          - unique
          - not_null

  - name: clientes_incremental
    description: "Tabla incremental que añade timestamp de carga"
    columns:
      - name: id
        tests:
          - unique
          - not_null
