name: "lakehouse_banking_pci"
version: "1.0.0"
config-version: 2

profile: "databricks_banking"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  default_currency: "USD"

on-run-start:
  - "{{ audit_run_start() }}"
on-run-end:
  - "{{ audit_run_end() }}"

models:
  lakehouse_banking_pci:

    # Hooks globales (considerar limitar a gold si crece el proyecto)
    +post-hook:
      - "{{ generate_bi_views(this) }}"
      - "{{ audit_model_execution(this) }}"

    bronze:
      +materialized: table
      +tags: ["bronze"]

    silver:
      +materialized: incremental
      +file_format: delta
      +tags: ["silver", "pci_compliant"]

      transactions:
        +incremental_strategy: merge
        +unique_key: "transaction_id"

        # 🔥 Merge determinista real
        +merge_update_columns:
          - amount_usd
          - transaction_type
          - card_number_hashed
          - record_hash

        # Clustering coherente con modelo
        +cluster_by:
          - customer_id
          - transaction_date_dt

    gold:
      +materialized: table
      +tags: ["gold"]

      customer_360:
        +materialized: materialized_view
        +cluster_by: ["customer_id"]

        +meta:
          schedule:
            cron: "0 0 * * * ?"