name: 'my_new_project'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configuración global para modelos y seeds
models:
  my_new_project:
    +schema: dbt_deygersonmndz
    +materialized: table
    +location_root: "dbfs:/user/hive/warehouse/dbt_deygersonmndz.db"

seeds:
  my_new_project:
    +schema: dbt_deygersonmndz
    +materialized: seed
    +location_root: "dbfs:/user/hive/warehouse/dbt_deygersonmndz.db"
